// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_challenges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :execrows
INSERT INTO used_auth_challenges (token_hash, expires_at)
SELECT $1::text, $2::timestamptz
WHERE $2::timestamptz > clock_timestamp()
ON CONFLICT (token_hash) DO NOTHING
`

type ConsumeAuthChallengeParams struct {
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ConsumeAuthChallenge(ctx context.Context, arg ConsumeAuthChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAuthChallenge, arg.TokenHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthChallenges = `-- name: DeleteExpiredAuthChallenges :exec
DELETE FROM used_auth_challenges WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAuthChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthChallenges)
	return err
}
