// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package db

import (
	"context"
)

const completeBootstrap = `-- name: CompleteBootstrap :exec
UPDATE server_bootstrap SET completed = true, token_hash = '' WHERE singleton = true
`

func (q *Queries) CompleteBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, completeBootstrap)
	return err
}

const getBootstrap = `-- name: GetBootstrap :one
SELECT singleton, completed, token_hash FROM server_bootstrap WHERE singleton = true
`

func (q *Queries) GetBootstrap(ctx context.Context) (ServerBootstrap, error) {
	row := q.db.QueryRow(ctx, getBootstrap)
	var i ServerBootstrap
	err := row.Scan(&i.Singleton, &i.Completed, &i.TokenHash)
	return i, err
}

const lockBootstrap = `-- name: LockBootstrap :one
SELECT singleton, completed, token_hash FROM server_bootstrap WHERE singleton = true FOR UPDATE
`

func (q *Queries) LockBootstrap(ctx context.Context) (ServerBootstrap, error) {
	row := q.db.QueryRow(ctx, lockBootstrap)
	var i ServerBootstrap
	err := row.Scan(&i.Singleton, &i.Completed, &i.TokenHash)
	return i, err
}

const setBootstrapTokenHash = `-- name: SetBootstrapTokenHash :exec
UPDATE server_bootstrap SET token_hash = $1 WHERE singleton = true AND completed = false
`

func (q *Queries) SetBootstrapTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, setBootstrapTokenHash, tokenHash)
	return err
}
