// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browser_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const browserSessionActive = `-- name: BrowserSessionActive :one
SELECT EXISTS(SELECT 1 FROM browser_sessions
 WHERE id = $1 AND user_id = $2 AND token_version = $3)
`

type BrowserSessionActiveParams struct {
	ID           string      `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	TokenVersion int64       `json:"token_version"`
}

func (q *Queries) BrowserSessionActive(ctx context.Context, arg BrowserSessionActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, browserSessionActive, arg.ID, arg.UserID, arg.TokenVersion)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBrowserSession = `-- name: CreateBrowserSession :exec
INSERT INTO browser_sessions (id, user_id, token_version) VALUES ($1, $2, $3)
`

type CreateBrowserSessionParams struct {
	ID           string      `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	TokenVersion int64       `json:"token_version"`
}

func (q *Queries) CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) error {
	_, err := q.db.Exec(ctx, createBrowserSession, arg.ID, arg.UserID, arg.TokenVersion)
	return err
}

const deleteBrowserSession = `-- name: DeleteBrowserSession :exec
DELETE FROM browser_sessions WHERE id = $1 AND user_id = $2
`

type DeleteBrowserSessionParams struct {
	ID     string      `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBrowserSession(ctx context.Context, arg DeleteBrowserSessionParams) error {
	_, err := q.db.Exec(ctx, deleteBrowserSession, arg.ID, arg.UserID)
	return err
}
