// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dav.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const calendarObjectWithUID = `-- name: CalendarObjectWithUID :one
SELECT uid FROM calendar_objects
WHERE calendar_id = $1
  AND parsed ->> 'uid' = $2::text
  AND uid <> $3
LIMIT 1
`

type CalendarObjectWithUIDParams struct {
	CalendarID pgtype.UUID `json:"calendar_id"`
	IcalUid    string      `json:"ical_uid"`
	ObjectUid  string      `json:"object_uid"`
}

// Another object of the collection that carries the iCalendar UID (RFC 4791 no-uid-conflict).
// Index: calendar_objects_ical_uid (migration 000019).
func (q *Queries) CalendarObjectWithUID(ctx context.Context, arg CalendarObjectWithUIDParams) (string, error) {
	row := q.db.QueryRow(ctx, calendarObjectWithUID, arg.CalendarID, arg.IcalUid, arg.ObjectUid)
	var uid string
	err := row.Scan(&uid)
	return uid, err
}

const createLinkShare = `-- name: CreateLinkShare :one
INSERT INTO resource_shares (resource_type, resource_id, owner_id, share_link_token, access, share_password_hash)
VALUES ($1, $2, $3, $4::text, $5, $6)
RETURNING id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash
`

type CreateLinkShareParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	Token        string      `json:"token"`
	Access       string      `json:"access"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

// A public link (feed) share, its password hash written in the same statement.
func (q *Queries) CreateLinkShare(ctx context.Context, arg CreateLinkShareParams) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, createLinkShare,
		arg.ResourceType,
		arg.ResourceID,
		arg.OwnerID,
		arg.Token,
		arg.Access,
		arg.PasswordHash,
	)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OwnerID,
		&i.SharedWithUser,
		&i.ShareLinkToken,
		&i.Access,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SharePasswordHash,
	)
	return i, err
}

const deleteSharesForResource = `-- name: DeleteSharesForResource :exec
DELETE FROM resource_shares WHERE resource_type = $1 AND resource_id = $2
`

type DeleteSharesForResourceParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

func (q *Queries) DeleteSharesForResource(ctx context.Context, arg DeleteSharesForResourceParams) error {
	_, err := q.db.Exec(ctx, deleteSharesForResource, arg.ResourceType, arg.ResourceID)
	return err
}

const upsertCollectionShare = `-- name: UpsertCollectionShare :one

INSERT INTO resource_shares (resource_type, resource_id, owner_id, shared_with_user, access, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (resource_type, resource_id, shared_with_user)
    WHERE shared_with_user IS NOT NULL AND resource_type IN ('calendar', 'addressbook')
DO UPDATE SET access = EXCLUDED.access, expires_at = EXCLUDED.expires_at
RETURNING id, resource_type, resource_id, owner_id, shared_with_user, share_link_token, access, expires_at, created_at, share_password_hash
`

type UpsertCollectionShareParams struct {
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	SharedWithUser pgtype.UUID        `json:"shared_with_user"`
	Access         string             `json:"access"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// CalDAV/CardDAV collections: sharing and integrity checks.
// Share a calendar or address book with a user; sharing it again with the same user
// updates the existing share (see migration 000019).
func (q *Queries) UpsertCollectionShare(ctx context.Context, arg UpsertCollectionShareParams) (ResourceShare, error) {
	row := q.db.QueryRow(ctx, upsertCollectionShare,
		arg.ResourceType,
		arg.ResourceID,
		arg.OwnerID,
		arg.SharedWithUser,
		arg.Access,
		arg.ExpiresAt,
	)
	var i ResourceShare
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OwnerID,
		&i.SharedWithUser,
		&i.ShareLinkToken,
		&i.Access,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SharePasswordHash,
	)
	return i, err
}
