// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rescan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRescanRequest = `-- name: CreateRescanRequest :one
INSERT INTO rescan_requests (user_id, requested_by) VALUES ($1, $2) RETURNING id, user_id, requested_by, created_at, started_at, finished_at, imported, missing, changed, errors, error_text
`

type CreateRescanRequestParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	RequestedBy string      `json:"requested_by"`
}

func (q *Queries) CreateRescanRequest(ctx context.Context, arg CreateRescanRequestParams) (RescanRequest, error) {
	row := q.db.QueryRow(ctx, createRescanRequest, arg.UserID, arg.RequestedBy)
	var i RescanRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Imported,
		&i.Missing,
		&i.Changed,
		&i.Errors,
		&i.ErrorText,
	)
	return i, err
}

const finishRescanRequest = `-- name: FinishRescanRequest :exec
UPDATE rescan_requests
SET finished_at = now(), imported = $2, missing = $3, changed = $4, errors = $5, error_text = $6
WHERE id = $1
`

type FinishRescanRequestParams struct {
	ID        int64       `json:"id"`
	Imported  int32       `json:"imported"`
	Missing   int32       `json:"missing"`
	Changed   int32       `json:"changed"`
	Errors    int32       `json:"errors"`
	ErrorText pgtype.Text `json:"error_text"`
}

func (q *Queries) FinishRescanRequest(ctx context.Context, arg FinishRescanRequestParams) error {
	_, err := q.db.Exec(ctx, finishRescanRequest,
		arg.ID,
		arg.Imported,
		arg.Missing,
		arg.Changed,
		arg.Errors,
		arg.ErrorText,
	)
	return err
}

const getRescanRequest = `-- name: GetRescanRequest :one
SELECT id, user_id, requested_by, created_at, started_at, finished_at, imported, missing, changed, errors, error_text FROM rescan_requests WHERE id = $1
`

func (q *Queries) GetRescanRequest(ctx context.Context, id int64) (RescanRequest, error) {
	row := q.db.QueryRow(ctx, getRescanRequest, id)
	var i RescanRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Imported,
		&i.Missing,
		&i.Changed,
		&i.Errors,
		&i.ErrorText,
	)
	return i, err
}

const listPendingRescanRequests = `-- name: ListPendingRescanRequests :many
SELECT id, user_id, requested_by, created_at, started_at, finished_at, imported, missing, changed, errors, error_text FROM rescan_requests WHERE finished_at IS NULL ORDER BY id
`

func (q *Queries) ListPendingRescanRequests(ctx context.Context) ([]RescanRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRescanRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RescanRequest{}
	for rows.Next() {
		var i RescanRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Imported,
			&i.Missing,
			&i.Changed,
			&i.Errors,
			&i.ErrorText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRescanRequests = `-- name: ListRecentRescanRequests :many
SELECT r.id, r.user_id, r.requested_by, r.created_at, r.started_at, r.finished_at, r.imported, r.missing, r.changed, r.errors, r.error_text, u.email
FROM rescan_requests r LEFT JOIN users u ON u.id = r.user_id
ORDER BY r.id DESC LIMIT $1
`

type ListRecentRescanRequestsRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RequestedBy string             `json:"requested_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Imported    int32              `json:"imported"`
	Missing     int32              `json:"missing"`
	Changed     int32              `json:"changed"`
	Errors      int32              `json:"errors"`
	ErrorText   pgtype.Text        `json:"error_text"`
	Email       pgtype.Text        `json:"email"`
}

func (q *Queries) ListRecentRescanRequests(ctx context.Context, limit int32) ([]ListRecentRescanRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRecentRescanRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentRescanRequestsRow{}
	for rows.Next() {
		var i ListRecentRescanRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Imported,
			&i.Missing,
			&i.Changed,
			&i.Errors,
			&i.ErrorText,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startRescanRequest = `-- name: StartRescanRequest :exec
UPDATE rescan_requests SET started_at = now() WHERE id = $1
`

func (q *Queries) StartRescanRequest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, startRescanRequest, id)
	return err
}
