// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUploadReservation = `-- name: AddUploadReservation :exec
UPDATE upload_reservations SET bytes=bytes+$2,touched_at=clock_timestamp() WHERE id=$1
`

type AddUploadReservationParams struct {
	ID    string `json:"id"`
	Bytes int64  `json:"bytes"`
}

func (q *Queries) AddUploadReservation(ctx context.Context, arg AddUploadReservationParams) error {
	_, err := q.db.Exec(ctx, addUploadReservation, arg.ID, arg.Bytes)
	return err
}

const createUploadReservation = `-- name: CreateUploadReservation :exec
INSERT INTO upload_reservations(id,user_id) VALUES($1,$2)
`

type CreateUploadReservationParams struct {
	ID     string      `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateUploadReservation(ctx context.Context, arg CreateUploadReservationParams) error {
	_, err := q.db.Exec(ctx, createUploadReservation, arg.ID, arg.UserID)
	return err
}

const deleteEmptyUploadReservation = `-- name: DeleteEmptyUploadReservation :exec
DELETE FROM upload_reservations WHERE id=$1 AND bytes=0
`

func (q *Queries) DeleteEmptyUploadReservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEmptyUploadReservation, id)
	return err
}

const deleteUploadReservation = `-- name: DeleteUploadReservation :exec
DELETE FROM upload_reservations WHERE id=$1
`

func (q *Queries) DeleteUploadReservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUploadReservation, id)
	return err
}

const getUploadReservation = `-- name: GetUploadReservation :one
SELECT id, user_id, bytes, touched_at FROM upload_reservations WHERE id=$1
`

func (q *Queries) GetUploadReservation(ctx context.Context, id string) (UploadReservation, error) {
	row := q.db.QueryRow(ctx, getUploadReservation, id)
	var i UploadReservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bytes,
		&i.TouchedAt,
	)
	return i, err
}

const listStaleUploadReservations = `-- name: ListStaleUploadReservations :many
SELECT id, user_id, bytes, touched_at FROM upload_reservations WHERE touched_at < $1 ORDER BY touched_at LIMIT 256
`

func (q *Queries) ListStaleUploadReservations(ctx context.Context, touchedAt pgtype.Timestamptz) ([]UploadReservation, error) {
	rows, err := q.db.Query(ctx, listStaleUploadReservations, touchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadReservation{}
	for rows.Next() {
		var i UploadReservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Bytes,
			&i.TouchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUploadQuota = `-- name: LockUploadQuota :exec
SELECT pg_advisory_xact_lock(749341217)
`

func (q *Queries) LockUploadQuota(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockUploadQuota)
	return err
}

const totalUploadReserved = `-- name: TotalUploadReserved :one
SELECT COALESCE(SUM(bytes),0)::bigint FROM upload_reservations
`

func (q *Queries) TotalUploadReserved(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalUploadReserved)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchUploadReservation = `-- name: TouchUploadReservation :exec
UPDATE upload_reservations SET touched_at=clock_timestamp() WHERE id=$1
`

func (q *Queries) TouchUploadReservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchUploadReservation, id)
	return err
}

const trimUploadReservation = `-- name: TrimUploadReservation :exec
UPDATE upload_reservations SET bytes=$2,touched_at=clock_timestamp() WHERE id=$1 AND bytes >= $2
`

type TrimUploadReservationParams struct {
	ID    string `json:"id"`
	Bytes int64  `json:"bytes"`
}

func (q *Queries) TrimUploadReservation(ctx context.Context, arg TrimUploadReservationParams) error {
	_, err := q.db.Exec(ctx, trimUploadReservation, arg.ID, arg.Bytes)
	return err
}

const userUploadReserved = `-- name: UserUploadReserved :one
SELECT COALESCE(SUM(bytes),0)::bigint FROM upload_reservations WHERE user_id=$1
`

func (q *Queries) UserUploadReserved(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, userUploadReserved, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
